services:
  petfit-web:
    container_name: petfit-web
    image: chaeheamin/petfit-web
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true
    environment:
      - TZ=Asia/Seoul

  petfit-nginx:
    image: nginx:latest
    container_name: petfit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
    depends_on:
      - petfit-web

  certbot:
      image: certbot/certbot
      container_name: petfit-certbot
      volumes:
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_conf:
  certbot_www:
