spring:
    application:
        name: petfit

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/petfit
        username: petfit
        password:

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

    kakao:
        auth:
          client: ${KAKAO_CLIENT_ID}
          redirect: ${KAKAO_REDIRECT_URI}



    jwt:
        issuer: ${JWT_ISSUER}
        secret: ${JWT_SECRET}
        access-token-time: 3600000  # 1 hour
        refresh-token-validity-seconds: 604800000  # 7 days
