# Local Application Configuration
spring:
  application:
    name: petfit

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petfit
    username: postgres
    password: jext-3rd-petfit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kakao:
    auth:
      admin: 74f521389d656a1e56c68d4223ccf874
      client: 84d27ea7be4ba339a95254c674c3c972
      redirect: http://localhost:5173/oauth/redirect

  jwt:
    issuer: cms3604@naver.com
    secret: ject-3rd-petfit
    access-token-time: 3600000  # 1 hour
    refresh-token-validity-seconds: 604800000  # 7 days

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: petfit-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  batch:
    job:
      enabled: false # 서버 시작 시 배치 작업을 바로 실행X

  mail:
    host: smtp.gmail.com
    port: 587 # SMTP 포트
    username: petfitofficial@gmail.com
    password: rcrabblnbuythyva # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  front:
    local: http://localhost:5173
    vercel: https://pet-fit-3rd-fe.vercel.app
    domain: http://localhost:5173
  backend:
    domain: http://localhost:8080
  swagger:
    server: 로컬 서버
    description: 펫핏 API 명세서입니다

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: caches

  endpoint:
    health:
      show-details: always

  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

info:
  my-app:
    any-value: someValue
    group: "@project.group@"
    artifact-id: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@sourceCompatibility@"
  made-by: petfit