name: Petfit-Backend CI/CD Production Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Create resources directory
        run: mkdir -p ./src/main/resources

      - name: Create and Upload application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo -e "${{secrets.PROD_APPLICATION}}" | base64 --decode > ./src/main/resources/application.yml
      - uses: actions/upload-artifact@v4
        with:
          name: application.yml
          path: ./src/main/resources/application.yml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t petfit-prod .

      - name: Run docker container on EC2
        run: |
          docker compose up -d petfit-prod
          docker image prune -f
        working-directory: /home/ubuntu